Algoritmo "Exercicio 6"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Area do triangulo
// Autor(a)    : Thiago
// Data atual  : 08/04/2022
Var
a, b ,c : inteiro
Inicio
escreva("=========Use esse programa para descobrir a area do triangulo=========")
Escreval("OBS: TODOS OS VALORES ESTARÃO EM cm!")
Escreval("a = ")
leia(a)
Escreval("b = ")
leia(b)

escreval("O triângulo tem area de = ", (b * a)/2)
Fimalgoritmo